### ISSUE TITLE
Getting same error when using "search4 -u USERNAME" in MacOS Terminal

### ISSUE THREAD

**Issue by karimelkheshen** [meanii/Search4#17]
input: search4 -u _example_
ouput:
     Traceback (most recent call last):
     File "search4.py", line 12, in <module>
         from search4.utils import banner, result
     File "/Users/karimkhechen/Library/Python/2.7/lib/python/site-packages/search4/search4.py", line 12, in <module>
         from search4.utils import banner, result
     ImportError: No module named utils

Locations : /Users/**_my_user_**/Library/Python/2.7/lib/python/site-packages/search4
                   /Users/**_my_user_**/Library/Python/2.7/search4

**Comment by rootVIII** [comment]
Why are you using Python2.7? Can you try with Python3?

**Comment by karimelkheshen** [comment]
For some reason, when I downloaded the program, the libraries, binaries, and executable got copied in both python2.7 and python3.7 folders. I tried running it with both but it seems the errors have a pattern of not finding the proper modules.
So to troubleshoot I moved all the libraries such as colorama, urllib, ...etc inside the search4 folder.

That stopped the "not finding module" errors, and leaves me with "unable to find search4.utils" to import the banner and result. It also says search4 is not a package.
I know this is definitely a problem with my mac setup because python on mac is really messy, especially that it comes with two default python versions which are hard to get rid of and start again.

Just to say : I also put the path of the binaries in $PATH, but it still says "search4 command not found". So all the mentioned error were when I was running it directly inside the folder as "python3 search4.py -u something"
Thanks again for your help.

**Comment by rootVIII** [comment]
hmmm I know that if you use homebrew to install python3, it should put python3 into /usr/local/bin (instead of /usr/bin where the system python2 is located) and then `pip3 install <package name>` should install into your python3 libs.

So if you want to install search4 with pip you should be able to run `pip3 install .` from the project directory... or `pip3 install git+https://github.com/0xknown/Search4` assuming that you used homebrew to install python3 and python3 is in your path.

I don't know why homebrew puts Python3 in /usr/local/bin. Python3 installs into /usr/bin on most Linux distros . But either way it will be in your path which is all you really need.

**Comment by karimelkheshen** [comment]
I feel so stupid.. You're right I shoud've used pip3 install not pip. 
Everything works fine now.
Thanks a alot 👍

**Comment by rootVIII** [comment]
No worries! Glad you got it figured out.
