### ISSUE TITLE
Which features can/should I add

### ISSUE THREAD

**Issue by fishbigger** [meanii/Search4#18]
Hi,
I love this tool and want to help develop it. Are there any features you would like me to work on to improve this tool? 
Thanks in advance.

**Comment by ghost** [comment]
Hey, thanks for reaching out. 
There are no as such features I can think of right now that search4 needs. But, it really needs false positive fixes and other minor improvements. Can you look for flase positives and fix it? There are only a few of them. 

For instance `https://giphy.com/<username>` only works if there is a user with the _username_ otherwise it just redirects to `https://giphy.com/explore/username/` which gives a 200 response. That's a false output for search4.
The sites listed in [issues](https://github.com/0xknown/Search4/blob/master/issues.md) have similar probelms.

Other than that any features from your side is warmly welcomed!

**Comment by fishbigger** [comment]
Thanks, I will work on fixing some false positives but I also had the idea that if it successfully finds a person it try to grab info about them, their bio or equivalent. What do you think?
Thanks.

**Comment by ghost** [comment]
I had some doubts but after thinking over it, the idea is very good!
I guess sure, why not? We can grab some of the most identical data for the specific sites. For example if it’s Twitter we can go for the date of creation of the Twitter handle. If it’s Instagram we can go for the account’s name. Altogether it will help a lot. Good idea indeed!

**Comment by soxoj** [comment]
Sorry for writing to the closed topic, but @fishbigger will it be interesting for you to contribute info [socid_extractor](https://github.com/soxoj/socid-extractor)? It's a tool to grab info about persons, which is used in the [Maigret](https://github.com/soxoj/maigret), the Sherlock fork.
